### ISSUE TITLE
Replace "curated" with a more accurate term

### ISSUE THREAD

**Issue by seagreen** [krispo/awesome-haskell#17]
None of lists of Hackage are actually curated, so, e.g. "JSON - a curated Hackage list" is inaccurate. 

Any ideas for a better term?

**Comment by silky** [comment]
collaborative

**Comment by krispo** [comment]
I like collaborative. any other variants, joint, shared, public, community driven?..

**Comment by seagreen** [comment]
I like comprehensive as well, but I think collaborative work too. Thanks for changing this so fast!
