### ISSUE TITLE
Underscore character in front of the "Basics" section

### ISSUE THREAD

**Issue by jaredpetersen** [krispo/awesome-haskell#8]
There is an underscore in front of the Haskell "Basics" section header and table of contents link. I'm not sure if it's intended or not, but it appears to be a nonstandard way of titling in the repo.

**Comment by AndreasLoow** [comment]
It's probably because everything else is in alphabetical order, and by that order "basics" would not be the first item in the list.

**Comment by krispo** [comment]
I've changed "Basics" with italic style. May be it's a bit better.
